/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.certus.ejemplo.gui.panels;

/**
 *
 * @author agust
 */
public class Sucursales extends javax.swing.JPanel {

    /**
     * Creates new form sucursales
     */
    public Sucursales() {
        initComponents();
         jLabel9.setVisible(false);
        jLabel10.setVisible(false);
        jLabel11.setVisible(false);
        jLabel12.setVisible(false);
        jLabel13.setVisible(false);
        jLabel14.setVisible(false);
        jLabel15.setVisible(false);
        jLabel16.setVisible(false);
        jLabel17.setVisible(false);
        jLabel18.setVisible(false);
        jLabel19.setVisible(false);
        jLabel20.setVisible(false);
        btnLinceLess.setVisible(false);
        btnMirafloresLess.setVisible(false);
        btnSJLLess.setVisible(false);
        btnSurcoLess.setVisible(false);
        btnChorrillosLess.setVisible(false);
        btnBarrancoLess.setVisible(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnSurcoMore = new javax.swing.JButton();
        btnSurcoLess = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnLinceMore = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnLinceLess = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnSJLMore = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        info3 = new javax.swing.JLabel();
        btnSJLLess = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnMirafloresMore = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnMirafloresLess = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btnBarrancoMore = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnBarrancoLess = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        btnChorrillosMore = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnChorrillosLess = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 102, 102));
        setForeground(new java.awt.Color(102, 102, 102));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Surco", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Falcon PUnCh!!", 3, 14))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/certus/ejemplo/gui/images/sucursal 1.jpg"))); // NOI18N

        btnSurcoMore.setBackground(new java.awt.Color(0, 51, 51));
        btnSurcoMore.setForeground(new java.awt.Color(255, 255, 255));
        btnSurcoMore.setText("VER MAS +");
        btnSurcoMore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSurcoMoreActionPerformed(evt);
            }
        });

        btnSurcoLess.setBackground(new java.awt.Color(0, 51, 51));
        btnSurcoLess.setForeground(new java.awt.Color(255, 255, 255));
        btnSurcoLess.setText("VER MENOS -");
        btnSurcoLess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSurcoLessActionPerformed(evt);
            }
        });

        jLabel9.setText("Direccion: Av. Caminos del Inca 1573                  ");

        jLabel10.setText("Telefono: 999 999 99 ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSurcoMore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3))
                    .addComponent(btnSurcoLess, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSurcoLess, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSurcoMore, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Lince", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Falcon PUnCh!!", 3, 14))); // NOI18N

        btnLinceMore.setBackground(new java.awt.Color(0, 51, 51));
        btnLinceMore.setForeground(new java.awt.Color(255, 255, 255));
        btnLinceMore.setText("VER MAS +");
        btnLinceMore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLinceMoreActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/certus/ejemplo/gui/images/sucursal 2.jpg"))); // NOI18N
        jLabel2.setText(" ");

        btnLinceLess.setBackground(new java.awt.Color(0, 51, 51));
        btnLinceLess.setForeground(new java.awt.Color(255, 255, 255));
        btnLinceLess.setText("VER MENOS -");
        btnLinceLess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLinceLessActionPerformed(evt);
            }
        });

        jLabel11.setText("Teléfono: 988 888 888");

        jLabel12.setText("Direccion: Av. Ignacio Merino 2492                   ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLinceMore, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLinceLess, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addGap(25, 25, 25)
                .addComponent(btnLinceLess, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLinceMore, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "San Juan de Lurigancho", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Falcon PUnCh!!", 3, 14))); // NOI18N

        btnSJLMore.setBackground(new java.awt.Color(0, 51, 51));
        btnSJLMore.setForeground(new java.awt.Color(255, 255, 255));
        btnSJLMore.setText("VER MAS +");
        btnSJLMore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSJLMoreActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/certus/ejemplo/gui/images/sucursal 3.jpg"))); // NOI18N
        jLabel4.setText(" ");

        info3.setText(" ");

        btnSJLLess.setBackground(new java.awt.Color(0, 51, 51));
        btnSJLLess.setForeground(new java.awt.Color(255, 255, 255));
        btnSJLLess.setText("VER MENOS -");
        btnSJLLess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSJLLessActionPerformed(evt);
            }
        });

        jLabel13.setText("Teléfono: 988 888 888");

        jLabel14.setText("Direccion: Av. Caminos del Inca 1573                  ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSJLMore, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(btnSJLLess, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(info3)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSJLLess, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(info3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSJLMore, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Miraflores", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Falcon PUnCh!!", 3, 14))); // NOI18N

        btnMirafloresMore.setBackground(new java.awt.Color(0, 51, 51));
        btnMirafloresMore.setForeground(new java.awt.Color(255, 255, 255));
        btnMirafloresMore.setText("VER MAS +");
        btnMirafloresMore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMirafloresMoreActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/certus/ejemplo/gui/images/sucursal 4.jpg"))); // NOI18N
        jLabel6.setText(" ");

        btnMirafloresLess.setBackground(new java.awt.Color(0, 51, 51));
        btnMirafloresLess.setForeground(new java.awt.Color(255, 255, 255));
        btnMirafloresLess.setText("VER MENOS -");
        btnMirafloresLess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMirafloresLessActionPerformed(evt);
            }
        });

        jLabel15.setText("Direccion: Av comandante espinar 865");

        jLabel16.setText("Teléfono: 988 888 888");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMirafloresMore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMirafloresLess, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel6))
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMirafloresLess, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMirafloresMore, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Barranco", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Falcon PUnCh!!", 3, 14))); // NOI18N

        btnBarrancoMore.setBackground(new java.awt.Color(0, 51, 51));
        btnBarrancoMore.setForeground(new java.awt.Color(255, 255, 255));
        btnBarrancoMore.setText("VER MAS +");
        btnBarrancoMore.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnBarrancoMoreFocusGained(evt);
            }
        });
        btnBarrancoMore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBarrancoMoreActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/certus/ejemplo/gui/images/sucursal 5.jpg"))); // NOI18N
        jLabel7.setText(" ");

        btnBarrancoLess.setBackground(new java.awt.Color(0, 51, 51));
        btnBarrancoLess.setForeground(new java.awt.Color(255, 255, 255));
        btnBarrancoLess.setText("VER MENOS -");
        btnBarrancoLess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBarrancoLessActionPerformed(evt);
            }
        });

        jLabel17.setText("Teléfono: 988 888 888");

        jLabel18.setText("Direccion: Av. San Martín 201                              ");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBarrancoLess, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBarrancoMore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnBarrancoLess, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBarrancoMore, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Chorrillos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Falcon PUnCh!!", 3, 14))); // NOI18N

        btnChorrillosMore.setBackground(new java.awt.Color(0, 51, 51));
        btnChorrillosMore.setForeground(new java.awt.Color(255, 255, 255));
        btnChorrillosMore.setText("VER MAS +");
        btnChorrillosMore.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnChorrillosMoreFocusGained(evt);
            }
        });
        btnChorrillosMore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChorrillosMoreActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/certus/ejemplo/gui/images/sucursal 6.jpg"))); // NOI18N
        jLabel8.setText(" ");

        btnChorrillosLess.setBackground(new java.awt.Color(0, 51, 51));
        btnChorrillosLess.setForeground(new java.awt.Color(255, 255, 255));
        btnChorrillosLess.setText("VER MENOS -");
        btnChorrillosLess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChorrillosLessActionPerformed(evt);
            }
        });

        jLabel19.setText("Direccion: Jr. Guardia Civil Sur 504                      ");

        jLabel20.setText("Teléfono: 988 888 888");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnChorrillosMore, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnChorrillosLess, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel20)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel8))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnChorrillosLess, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnChorrillosMore, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel21.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("SUCURSALES");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel21)
                .addGap(365, 365, 365))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel21)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBarrancoMoreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnBarrancoMoreFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBarrancoMoreFocusGained

    private void btnLinceMoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLinceMoreActionPerformed
        // TODO add your handling code here:
        jLabel2.setVisible(false);
        jLabel11.setVisible(true);
        jLabel12.setVisible(true);
        btnLinceMore.setVisible(false);
        btnLinceLess.setVisible(true);
        
    }//GEN-LAST:event_btnLinceMoreActionPerformed

    private void btnSJLMoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSJLMoreActionPerformed
        // TODO add your handling code here:
        jLabel4.setVisible(false);
        jLabel13.setVisible(true);
        jLabel14.setVisible(true);
        btnSJLMore.setVisible(false);
        btnSJLLess.setVisible(true);
        
    }//GEN-LAST:event_btnSJLMoreActionPerformed

    private void btnBarrancoMoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBarrancoMoreActionPerformed
        // TODO add your handling code here:
        jLabel7.setVisible(false);
        jLabel17.setVisible(true);
        jLabel18.setVisible(true);
        btnBarrancoMore.setVisible(false);
        btnBarrancoLess.setVisible(true);
        
    }//GEN-LAST:event_btnBarrancoMoreActionPerformed

    private void btnMirafloresMoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMirafloresMoreActionPerformed
        // TODO add your handling code here:
        jLabel6.setVisible(false);
        jLabel15.setVisible(true);
        jLabel16.setVisible(true);
        btnMirafloresMore.setVisible(false);
        btnMirafloresLess.setVisible(true);
        

    }//GEN-LAST:event_btnMirafloresMoreActionPerformed

    private void btnLinceLessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLinceLessActionPerformed
        // TODO add your handling code here:
        jLabel2.setVisible(true);
        jLabel11.setVisible(false);
        jLabel12.setVisible(false);
        btnLinceMore.setVisible(true);
        btnLinceLess.setVisible(false);
    }//GEN-LAST:event_btnLinceLessActionPerformed

    private void btnSJLLessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSJLLessActionPerformed
        // TODO add your handling code here:
        jLabel4.setVisible(true);
        jLabel13.setVisible(false);
        jLabel14.setVisible(false);
        btnSJLMore.setVisible(true);
        btnSJLLess.setVisible(false);
                                              
    }//GEN-LAST:event_btnSJLLessActionPerformed

    private void btnMirafloresLessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMirafloresLessActionPerformed
        // TODO add your handling code here:
         jLabel6.setVisible(true);
        jLabel15.setVisible(false);
        jLabel16.setVisible(false);
        btnMirafloresMore.setVisible(true);
        btnMirafloresLess.setVisible(false);
    }//GEN-LAST:event_btnMirafloresLessActionPerformed

    private void btnBarrancoLessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBarrancoLessActionPerformed
        // TODO add your handling code here:
        jLabel7.setVisible(true);
        jLabel17.setVisible(false);
        jLabel18.setVisible(false);
        btnBarrancoMore.setVisible(true);
        btnBarrancoLess.setVisible(false);
    }//GEN-LAST:event_btnBarrancoLessActionPerformed

    private void btnChorrillosLessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChorrillosLessActionPerformed
        // TODO add your handling code here:
        jLabel8.setVisible(true);
        jLabel19.setVisible(false);
        jLabel20.setVisible(false);
        btnChorrillosMore.setVisible(true);
        btnChorrillosLess.setVisible(false);
    }//GEN-LAST:event_btnChorrillosLessActionPerformed

    private void btnChorrillosMoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChorrillosMoreActionPerformed
        // TODO add your handling code here:
        //jLabel8.setVisible(false);
        jLabel19.setVisible(true);
        jLabel20.setVisible(true);
        btnChorrillosMore.setVisible(false);
        btnChorrillosLess.setVisible(true);

    }//GEN-LAST:event_btnChorrillosMoreActionPerformed

    private void btnChorrillosMoreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnChorrillosMoreFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_btnChorrillosMoreFocusGained

    private void btnSurcoLessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSurcoLessActionPerformed
        // TODO add your handling code here:
        jLabel3.setVisible(true);
        jLabel9.setVisible(false);
        jLabel10.setVisible(false);
        btnSurcoMore.setVisible(true);
        btnSurcoLess.setVisible(false);
    }//GEN-LAST:event_btnSurcoLessActionPerformed

    private void btnSurcoMoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSurcoMoreActionPerformed
        // TODO add your handling code here:
        jLabel3.setVisible(false);
        jLabel9.setVisible(true);
        jLabel10.setVisible(true);
        btnSurcoMore.setVisible(false);
        btnSurcoLess.setVisible(true);

    }//GEN-LAST:event_btnSurcoMoreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBarrancoLess;
    private javax.swing.JButton btnBarrancoMore;
    private javax.swing.JButton btnChorrillosLess;
    private javax.swing.JButton btnChorrillosMore;
    private javax.swing.JButton btnLinceLess;
    private javax.swing.JButton btnLinceMore;
    private javax.swing.JButton btnMirafloresLess;
    private javax.swing.JButton btnMirafloresMore;
    private javax.swing.JButton btnSJLLess;
    private javax.swing.JButton btnSJLMore;
    private javax.swing.JButton btnSurcoLess;
    private javax.swing.JButton btnSurcoMore;
    private javax.swing.JLabel info3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    // End of variables declaration//GEN-END:variables
}
