/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.certus.ejemplo.gui;

import com.certus.ejemplo.gui.panels.Pedidos1;
import com.certus.ejemplo.gui.panels.PnlCliente;
import com.certus.ejemplo.gui.panels.Productos;
import com.certus.ejemplo.gui.panels.Sucursales;
import com.certus.ejemplo.gui.Interfaz;
import java.awt.BorderLayout;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author AROM
 */
public class Interfaz extends javax.swing.JFrame {
    Pedidos1 pedido = new Pedidos1();
    Productos producto = new Productos();
    PnlCliente cliente = new PnlCliente();
    Sucursales sucursal = new Sucursales();
    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        
        Panel.setLayout(new BorderLayout());
        Panel.add(producto);
        setIconImage(new ImageIcon(getClass().getResource("/com/certus/ejemplo/gui/images/pizza.png")).getImage());
        setTitle("Pizza Pizza - User");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        Panel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Sucursales = new javax.swing.JMenuItem();
        opcPedidos = new javax.swing.JMenuItem();
        opcProductos = new javax.swing.JMenuItem();
        Cerrar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        opcClientes = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 627, Short.MAX_VALUE)
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 607, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(Panel);

        jMenu1.setText("Inicio");

        Sucursales.setText("Sucursales");
        Sucursales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SucursalesActionPerformed(evt);
            }
        });
        jMenu1.add(Sucursales);

        opcPedidos.setBackground(new java.awt.Color(102, 102, 102));
        opcPedidos.setText("Pedidos");
        opcPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcPedidosActionPerformed(evt);
            }
        });
        jMenu1.add(opcPedidos);

        opcProductos.setBackground(new java.awt.Color(102, 102, 102));
        opcProductos.setText("Prductos");
        opcProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcProductosActionPerformed(evt);
            }
        });
        jMenu1.add(opcProductos);

        Cerrar.setBackground(new java.awt.Color(102, 102, 102));
        Cerrar.setForeground(new java.awt.Color(153, 153, 153));
        Cerrar.setText("Cerrar");
        Cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarActionPerformed(evt);
            }
        });
        jMenu1.add(Cerrar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Socios");

        opcClientes.setText("Clientes");
        opcClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcClientesActionPerformed(evt);
            }
        });
        jMenu2.add(opcClientes);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarActionPerformed
        // TODO add your handling code here:
                int op = JOptionPane.showConfirmDialog(this, 
                                "Deseas Salir?", 
                                "Estas seguro que deseas cerrar el sistema?", 
                                JOptionPane.OK_CANCEL_OPTION);
                if(op==0)  System.exit(0);
    }//GEN-LAST:event_CerrarActionPerformed

    private void SucursalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SucursalesActionPerformed
        // TODO add your handling code here:
        Panel.removeAll();
        Panel.add(sucursal);
        SwingUtilities.updateComponentTreeUI(Panel);
    }//GEN-LAST:event_SucursalesActionPerformed

    private void opcPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcPedidosActionPerformed
        // TODO add your handling code here:
        Panel.removeAll();
        Panel.add(pedido);
        SwingUtilities.updateComponentTreeUI(Panel);
    }//GEN-LAST:event_opcPedidosActionPerformed

    private void opcProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcProductosActionPerformed
        // TODO add your handling code here:
        Panel.removeAll();
        Panel.add(producto);
        SwingUtilities.updateComponentTreeUI(Panel);
        
    }//GEN-LAST:event_opcProductosActionPerformed

    private void opcClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcClientesActionPerformed
        // TODO add your handling code here:
        Panel.removeAll();
        Panel.add(cliente);
        SwingUtilities.updateComponentTreeUI(Panel);
    }//GEN-LAST:event_opcClientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Cerrar;
    private javax.swing.JPanel Panel;
    private javax.swing.JMenuItem Sucursales;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem opcClientes;
    private javax.swing.JMenuItem opcPedidos;
    private javax.swing.JMenuItem opcProductos;
    // End of variables declaration//GEN-END:variables
}
